spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/meeting_rooms
    username:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update